name: UI Linting
on: push

jobs:
  lint:
    name: Lint UI code base
    runs-on: ubuntu-latest
    with:
          fetch-depth: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint UI
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          DEFAULT_BRANCH: dev
          FILTER_REGEX_INCLUDE: .*[.]jss | .*[.]html | .*[.css]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}