name: Notebook Linting
on: [push]
jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jupyter
        run: pip3 install --upgrade --force-reinstall --no-cache-dir jupyter

      - name: Convert notebooks to Python
        run: find . -type f -name "*.ipynb" -exec jupyter nbconvert --to python --TemplateExporter.exclude_markdown=true {} \;

      - name: Convert notebooks to Markdown
        run: find . -type f -name "*.ipynb" -exec jupyter nbconvert --to markdown --TemplateExporter.exclude_code_cell=true {} \;

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: dev
          FILTER_REGEX_INCLUDE: .*src/notebooks.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}